import sys

with open('assets/css/style.css', 'r', encoding='utf-8') as f:
    content = f.read()

replacements = {
    "/* ---------- Google Fonts ---------- */": "/* ---------- Fuentes de Google ---------- */",
    "DESIGN TOKENS — Bleach Manga Palette": "TOKENS DE DISEÑO — Paleta Manga Bleach",
    "── Paper & Ink (Core manga feel) ──": "── Papel y Tinta (Sensación manga base) ──",
    "aged manga page": "página de manga envejecida",
    "bright page areas": "áreas brillantes de la página",
    "mid-tone paper": "papel de tono medio",
    "shadow areas on paper": "áreas de sombra en el papel",
    "heavily worn edges": "bordes muy desgastados",
    "deep manga ink": "tinta oscura de manga",
    "slightly lifted ink": "tinta ligeramente más clara",
    "halftone dark areas": "áreas oscuras de semitono",
    "── Bleach Accent Colors ──": "── Colores de Acento Bleach ──",
    "Ichigo's spirit energy": "energía espiritual de Ichigo",
    "hot orange glow": "resplandor naranja cálido",
    "Hollow mask / spirit pressure": "máscara Hollow / presión espiritual",
    "bright teal accent": "acento verde azulado brillante",
    "Crimson dark red": "rojo oscuro carmesí",
    "Bright blood accent": "acento de sangre brillante",
    "energy spark / neon": "chispa de energía / neón",
    "halftone dots": "puntos de semitono (screentone)",
    "── Panel & Border ──": "── Panel y Bordes ──",
    "── Text ──": "── Texto ──",
    "── Typography ──": "── Tipografía ──",
    "── Font Sizes ──": "── Tamaños de Fuente ──",
    "── Spacing ──": "── Espaciado ──",
    "── Transitions ──": "── Transiciones ──",
    "── Layout ──": "── Diseño / Estructura ──",
    "RESET": "RESETEO (Estilos Base)",
    "── Aged paper base ──": "── Base de papel envejecido ──",
    "── Layered paper texture ──": "── Textura de papel en capas ──",
    "1. Halftone screentone dots": "1. Puntos de semitono (screentone)",
    "2. Paper grain noise": "2. Ruido de grano de papel",
    "3. Vertical scan lines (print artifact)": "3. Líneas verticales (artefacto de impresión)",
    "4. Edge vignette": "4. Viñeteado en los bordes",
    "soft vignette": "viñeteado suave",
    "screentone dots overlay": "superposición de puntos de semitono",
    "paper grain (coarse)": "grano de papel (rugoso)",
    "yellowed page gradient": "degradado de página amarillenta",
    "Ink splatter overlay on body": "Superposición de salpicaduras de tinta en el body",
    "worn corner stains": "manchas de desgaste en las esquinas",
    "Manga print artifact — global noise overlay": "Artefacto de impresión manga — superposición de ruido global",
    "UTILITY": "CLASES DE UTILIDAD",
    "── Manga screentone utility ──": "── Utilidad de screentone Manga ──",
    "HEADER — Ink bar on aged paper": "CABECERA — Barra de tinta en papel envejecido",
    "Mobile Menu": "Menú Móvil",
    "MAIN CONTENT": "CONTENIDO PRINCIPAL",
    "Scroll-reveal": "Animación al hacer scroll",
    "HERO SECTION — Ink splash on dark": "SECCIÓN HERO (Inicio) — Salpicadura de tinta",
    "Speed lines — radial burst from center": "Líneas de velocidad (Speed lines) — explosión radial desde el centro",
    "Dark screentone texture on hero": "Textura de screentone oscura en la sección Hero",
    "Orange reiatsu blast — right side": "Explosión de reiatsu naranja — lado derecho",
    "Teal hollow energy — left side": "Energía Hollow verde azulada — lado izquierdo",
    "Badge — manga chapter label": "Insignia — etiqueta de capítulo de manga",
    "Hero title — white impact on black, orange accent": "Título Hero — texto blanco impactante, acento naranja",
    "Ink text feel — slight roughness": "Sensación de texto en tinta — ligera aspereza",
    "Subtitle — on paper banner": "Subtítulo — sobre un cartel de papel",
    "BUTTONS — Manga panel brutaliste": "BOTONES — Paneles Manga",
    "Scroll indicator": "Indicador de desplazamiento (Scroll)",
    "SECTION STRUCTURE — Paper background": "ESTRUCTURA DE SECCIONES — Fondo de papel",
    "Alternating dark sections": "Secciones oscuras alternadas",
    "screentone on dark": "screentone sobre fondo oscuro",
    "Section headers": "Cabeceras de sección",
    "Ink text shadow — print feel": "Sombra de texto en tinta — sensación de impresión",
    "Ink gradient divider": "Divisor con degradado de tinta",
    "ABOUT SECTION — Manga profile panel": "SECCIÓN SOBRE MÍ — Panel de perfil de manga",
    "Portrait as manga panel": "Retrato como panel de manga",
    "Panel screentone inside portrait": "Screentone de panel dentro del retrato",
    "Diagonal slash — action line": "Corte diagonal — línea de acción",
    "Bio content": "Contenido de la biografía",
    "Stats — like manga info boxes": "Estadísticas — como cajas de información manga",
    "PROJECT CARDS — Manga action panels / viñetas": "TARJETAS DE PROYECTOS — Paneles de acción manga / viñetas",
    "Panel layout — like a manga page": "Diseño del grid — como una página de manga",
    "wide left": "ancho a la izquierda",
    "wide right": "ancho a la derecha",
    "narrow": "estrecho",
    "wider": "más ancho",
    "Panel number — top left corner like manga": "Número del panel — esquina superior izquierda",
    "Speed lines from top-right corner on hover": "Líneas de velocidad en la esquina superior derecha al pasar el cursor",
    "Panel thumbnail — manga scene": "Miniatura del panel — escena de manga",
    "Screentone overlay on thumbnail": "Superposición de screentone en miniatura",
    "Diagonal slash lines — action": "Líneas diagonales — acción",
    "Overlay — dark scrim + demo button": "Superposición — capa oscura + botón de demo",
    "screentone on overlay": "screentone sobre superposición",
    "Project info area — caption box style": "Área de información del proyecto — estilo de caja de texto",
    "CONTACT SECTION — Paper warmth": "SECCIÓN DE CONTACTO — Calidez del papel",
    "Ink stain top edge": "Mancha de tinta en el borde superior",
    "Social cards — manga info panel style": "Tarjetas sociales — estilo de panel de información manga",
    "Contact Form — panel on paper": "Formulario de Contacto — panel en el papel",
    "FOOTER — Bottom ink bar": "PIE DE PÁGINA (Footer) — Barra inferior de tinta",
    "LOADER": "CARGADOR (Loader)",
    "RESPONSIVE": "DISEÑO RESPONSIVO (Mobile)"
}

for k, v in replacements.items():
    content = content.replace(k, v)

with open('assets/css/style.css', 'w', encoding='utf-8') as f:
    f.write(content)

print('Done')
